# overlays/dev/externalsecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chatguard-secrets 
  namespace: chatguard
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: team1-dev-aws-secret-store
    kind: ClusterSecretStore
  target:
    name: chatguard-secrets 
  
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "rds!db-85d4f3b7-cc74-4b57-a4df-123456789abc"
        property: "password"
    - secretKey: DB_USER
      remoteRef:
        key: "rds!db-85d4f3b7-cc74-4b57-a4df-123456789abc"
        property: "username"

  - secretKey: JWT_SECRET
    remoteRef:
      key: "team1-dev-database-credentials"
      property: "JWT_SECRET"
