# overlays/dev/externalsecret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: chatguard-secrets 
  namespace: chatguard
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: team1-dev-aws-secret-store
    kind: ClusterSecretStore
  target:
    name: chatguard-secrets 
  
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "rds!db-95a46630-9750-4c73-b9a8-7e7bf7f7c5a5"
        property: "password"
    - secretKey: DB_USER
      remoteRef:
        key: "rds!db-95a46630-9750-4c73-b9a8-7e7bf7f7c5a5"
        property: "username"

    - secretKey: JWT_SECRET
      remoteRef:
        key: "team1-dev-database-credentials"
        property: "JWT_SECRET"
