apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chatguard
namePrefix: team1-dev-

resources:
- ../../base
- externalsecret.yaml
- clustersecretstore.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
    spec:
      replicas: 1
- path: patches/ingress-tags.yaml

images:
- name: team1-dev-ai-worker
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-dev-ai-worker
  newTag: cdbe8f543aaa3d0f3ccb2b8ccf06017f16fcb421
- name: team1-dev-api-server
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-dev-api-server
  newTag: cdbe8f543aaa3d0f3ccb2b8ccf06017f16fcb421
- name: team1-dev-frontend
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-dev-frontend
  newTag: cdbe8f543aaa3d0f3ccb2b8ccf06017f16fcb421

configurations:
- configurations/secret-name-reference.yaml
