# overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chatguard
namePrefix: team1-dev-

resources:
- ../../base

patches:
- path: replicas-patch.yaml
- path: patches/ingress-tags.yaml

images:
- name: team1-dev-ai-worker
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-dev-ai-worker
  newTag: c4552b56503873161a252308315a915c2ad0f216
- name: team1-dev-api-server
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-dev-api-server
  newTag: c4552b56503873161a252308315a915c2ad0f216
- name: team1-dev-frontend
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-dev-frontend
  newTag: c4552b56503873161a252308315a915c2ad0f216

configurations:
- configurations/secret-name-reference.yaml
