apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chatguard
namePrefix: team1-dev-

resources:
- ../../base
- externalsecret.yaml
- clustersecretstore.yaml
- prometheus-rules-dev.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
    spec:
      replicas: 1
- path: patches/ingress-tags.yaml

images:
- name: team1-dev-ai-worker
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-dev-ai-worker
  newTag: 7529909784177712d6eebad2e205b50cd50b0daf
- name: team1-dev-api-server
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-dev-api-server
  newTag: 7529909784177712d6eebad2e205b50cd50b0daf
- name: team1-dev-frontend
  newName: 495599735720.dkr.ecr.ap-northeast-2.amazonaws.com/team1-dev-frontend
  newTag: 7529909784177712d6eebad2e205b50cd50b0daf

configurations:
- configurations/secret-name-reference.yaml
