apiVersion: v1
kind: ServiceAccount
metadata:
  name: team1-dev-api-server-sa
  namespace: chatguard
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::495599735720:role/team1-dev-chat-server-s3-role
